src/Components/Fixture.cs, src/Components/TestComponentBase.cs
* Make WaitForNextRender asynchronous, instead of blocking until NextRender Task is completed. Blocking on task may lead to deadlocks.
* Add support for asynchronous tests in Fixture so that WaitForNextRender can be called properly.
=> Make WaitForNextRender method asynchronous

sample/tests/RazorTestComponents/Components/ThemedButtonTest.razor, src/Asserting/CompareToDiffingExtensions.cs, src/Asserting/MarkupMatchesAssertExtensions.cs, src/Asserting/ShouldBeAdditionAssertExtensions.cs, src/Asserting/ShouldBeRemovalAssertExtensions.cs, src/Asserting/ShouldBeTextChangeAssertExtensions.cs, src/Rendering/IRenderedFragment.cs, src/Rendering/RenderedComponent.cs, src/Rendering/RenderedFragment.cs, src/Rendering/RenderedFragmentBase.cs, tests/Asserting/CompareToDiffingExtensionsTest.cs, tests/ComponentTestFixtureTest.cs, tests/Components/TestComponentBaseTest/BlazorElementReferencesIncludedInRenderedMarkup.razor, tests/Components/TestComponentBaseTest/GettingCutAndFragmentFromRazorTestContextTest.razor, tests/RenderComponentTest.cs, tests/RenderedFragmentTest.cs
This is an implementation of the #28 issue.
@duracellko / @Siphonophora, since you are my first contributors, would you mind looking over this and giving me your feedback.
I like this change, but would like a sanity check from you guys.
=> Change GetNodes and GetMarkup to Nodes and Markup properties in IRenderedFragment

sample/tests/Tests/Components/AlertTest.cs, sample/tests/Tests/Components/FocussingInputTest.cs, sample/tests/Tests/Components/TodoListTest.cs, sample/tests/Tests/Components/WikiSearchTest.cs, sample/tests/_Imports.razor, src/Mocking/JSInterop/JsInvokeCountExpectedException.cs, src/Mocking/JSInterop/JsRuntimeAssertExtensions.cs, src/Mocking/JSInterop/JsRuntimeInvocation.cs, src/Mocking/JSInterop/JsRuntimeMockMode.cs, src/Mocking/JSInterop/JsRuntimePlannedInvocation.cs, src/Mocking/JSInterop/MockJsRuntimeInvokeHandler.cs, src/Mocking/JSInterop/UnplannedJsInvocationException.cs, src/Mocking/MockJsRuntimeExtensions.cs, template/template/Component1Test.cs, template/template/_Imports.razor, tests/Mocking/JSInterop/MockJsRuntimeInvokeHandlerTest.cs
This is a solution to #30.
@duracellko / @Siphonophora, would you mind looking over this and giving me your feedback.
=> Add SetupVoid and SetVoidResult capabilities to JsRuntime mock

docs/docs/creating-a-new-test-project.md
Typo: "past" should be "paste"
=> Typo: "past" should be "paste"

src/bunit.web.tests/Rendering/Internal/HtmlizerTests.cs, src/bunit.web/Rendering/Internal/Htmlizer.cs
Signed-off-by: samtrion <me@samtrion.net>
=> Fixed Internal Attributes #111

CHANGELOG.md, src/bunit.core/Rendering/ComponentDisposedException.cs, src/bunit.core/Rendering/RenderEvent.cs, src/bunit.core/Rendering/TestRenderer.cs, src/bunit.testassets/SampleComponents/ToggleChildComponent.razor, src/bunit.web.tests/Rendering/RenderedComponentTest.cs, src/bunit.web.tests/Rendering/RenderedFragmentTest.cs, src/bunit.web/Rendering/RenderedComponent.cs, src/bunit.web/Rendering/RenderedFragment.cs
=> Better handling of disposed components - fixes #175

CHANGELOG.md, src/Directory.Build.props, src/bunit.web/Rendering/Internal/Htmlizer.cs, tests/Directory.Build.props, tests/bunit.testassets/SampleComponents/ScopedCssElements.razor, tests/bunit.testassets/SampleComponents/ScopedCssElements.razor.css, tests/bunit.testassets/bunit.testassets.csproj, tests/bunit.web.tests/Asserting/MarkupMatchesAssertExtensionsTest.net5.cs, tests/bunit.web.tests/Rendering/Internal/HtmlizerTests.cs, tests/bunit.web.tests/Rendering/Internal/HtmlizerTests.net5.cs
=> Added support for scoped css attribute

CHANGELOG.md, docs/samples/components/UserInfo.razor, docs/samples/components/UserRights.razor, docs/samples/tests/xunit/InjectAuthServiceTest.cs, docs/samples/tests/xunit/UserInfoTest.cs, docs/samples/tests/xunit/UserRightsTest.cs, docs/site/docs/test-doubles/faking-auth.md, src/bunit.web/TestDoubles/Authorization/FakeAuthorizationExtensions.cs, tests/bunit.testassets/SampleComponents/SimpleAuthViewWithClaims.razor, tests/bunit.testassets/SampleComponents/SimpleAuthViewWithPolicy.razor, tests/bunit.testassets/SampleComponents/SimpleAuthViewWithRole.razor, tests/bunit.web.tests/TestDoubles/Authorization/AuthorizationTest.cs, tests/bunit.web.tests/TestDoubles/Authorization/TestAuthorizationContextTest.cs
`AddTestAuthorization` now extends `TestContext` instead of `TestServiceProvider`, and also automatically adds the `CascadingAuthenticationState` component to the root render tree
Closes #171.
=> AddTestAuthorization adds CascadingAuthenticationState to render tree

CHANGELOG.md, src/bunit.web/EventDispatchExtensions/DetailsElementEventDispatcherExtensions.cs, tests/bunit.testassets/SampleComponents/ToggleableDetails.razor, tests/bunit.web.tests/EventDispatchExtensions/DetailsElementEventDispatcherExtensionsTest.cs
=> Added event trigger extension method for @ontoggle

CHANGELOG.md, src/bunit.core/RazorTesting/FragmentContainer.cs, src/bunit.core/TestContextBase.cs, src/bunit.core/TestServiceProvider.cs, src/bunit.web/Asserting/MarkupMatchesAssertExtensions.cs, src/bunit.web/Extensions/Internal/AngleSharpExtensions.cs, src/bunit.web/Extensions/TestContextExtensions.cs, src/bunit.web/Extensions/TestServiceProviderExtensions.cs, src/bunit.web/IRenderedFragment.cs, src/bunit.web/RazorTesting/Fixture.cs, src/bunit.web/RazorTesting/SnapshotTest.cs, src/bunit.web/Rendering/BunitHtmlParser.cs, src/bunit.web/TestContext.cs, tests/bunit.core.tests/Rendering/TestRendererTest.cs, tests/bunit.web.tests/Asserting/MarkupMatchesAssertExtensionsTest.cs, tests/bunit.web.tests/Asserting/MarkupMatchesAssertExtensionsTest.net5.cs, tests/bunit.web.tests/RazorTesting/FixtureTest.razor, tests/bunit.web.tests/TestContextTest.cs
This PR adds support for cleaner razor based tests by making it possible for TestContext type to render RenderFragment's. This allows us to pass RenderFragments created inline in .razor files directly to the TestContext.
Also added support for passing RenderFragments to MarkupMatches' expected argument. This looks like this in practice, e.g. in a `CounterTest.razor` file:
```razor
@inherits TestContext
@code
{
[Fact]
public void Test()
{
var cut = Render(@<Counter />);
cut.Find("button").Click();
cut.Find("p").MarkupMatches(@<p>Current count: 1</p>);
}
}
```
=> TestContext.Render(renderFragment) and MarkupMatches(renderFragment)

CHANGELOG.md, src/bunit.core/TestServiceProvider.cs, tests/bunit.core.tests/TestServiceProviderTest.cs, tests/bunit.core.tests/TestServiceProviderTest.net5.cs
=> Added IAsyncDisposable to TestServiceProvider

docs/site/docs/test-doubles/emulating-ijsruntime.md
This fixes issue #308 that I ran into.
=> 308 Documentation on setting IJSRuntime mock to loose is incorrect

.editorconfig, CHANGELOG.md, src/bunit.core/Extensions/WaitForHelpers/RenderedFragmentWaitForHelperExtensions.cs, src/bunit.core/Extensions/WaitForHelpers/WaitForHelper.cs, src/bunit.core/Rendering/ITestRenderer.cs, src/bunit.core/Rendering/TestRenderer.cs, src/bunit.web/Extensions/RenderedFragmentExtensions.cs, tests/.editorconfig, tests/bunit.core.tests/ComponentParameterCollectionTest.cs, tests/bunit.core.tests/Extensions/WaitForHelpers/RenderedFragmentWaitForHelperExtensionsTest.cs, tests/bunit.core.tests/Rendering/TestRendererTest.cs, tests/bunit.web.tests/Asserting/JSRuntimeAssertExtensionsTest.cs
Add option to get any unhandled exception caught by the renderer.
Closes #319.
or targeted at `main` branch for documentation that is live on bunit.egilhansen.com.
=> Add option to get any unhandled exception caught by the renderer

.github/workflows/docs-deploy.yml
Hi @egil
This PR was created because the [docs-deploy](https://github.com/bUnit-dev/bUnit/actions/runs/799265259) failed to automatically merge stable into main.
=> Update main with documentation in stable

.editorconfig, CHANGELOG.md, Directory.Build.props, src/.editorconfig, src/bunit.core/ComponentFactories/ComponentFactoryCollectionExtensions.cs, src/bunit.core/ComponentFactories/ComponentFactoryCollectionStubExtensions.cs, src/bunit.core/ComponentFactories/DummyComponentFactory.cs, src/bunit.core/ComponentFactories/GenericComponentFactory{TComponent,TReplacementComponent}.cs, src/bunit.core/ComponentFactories/ShallowRenderComponentFactory.cs, src/bunit.core/ComponentFactories/StubComponentFactory.cs, src/bunit.core/TestDoubles/Components/ComponentDoubleFactory.cs, src/bunit.core/TestDoubles/Components/Dummy{TComponent}.cs, src/bunit.core/TestDoubles/Components/StubOptions.cs, src/bunit.core/TestDoubles/Components/Stub{TComponent}.cs, src/bunit.web/Extensions/RenderedFragmentExtensions.cs, src/bunit.web/Rendering/BunitHtmlParser.cs, stylecop.json, tests/.editorconfig, tests/bunit.core.tests/ComponentFactories/DummyComponentFactoryTest.cs, tests/bunit.core.tests/ComponentFactories/GenericComponentFactoryTest.cs, tests/bunit.core.tests/ComponentFactories/StubComponentFactoryTest.cs, tests/bunit.core.tests/TestDoubles/Components/DummyTest.cs, tests/bunit.core.tests/TestDoubles/Components/StubTest.cs, tests/bunit.testassets/SampleComponents/RefToSimple1Child.razor
=> Test double components 

CHANGELOG.md, src/bunit.web/Asserting/MarkupMatchesAssertExtensions.cs, tests/bunit.web.tests/Asserting/MarkupMatchesAssertExtensionsTest.cs
Related to #422.
Add more extensions to MarkupMatchesAssertExtensions to allow asserting on MarkupMatches from IEnumerable<IElement> and IElement
=> Markup matches combinations

docs/samples/tests/razor/RenderFragmentParams2Test.razor
In the doc, it is clearly said that the child component is the Counter component, but in the .razor file sample, the child component used is the Alert component which is also different from the C# sample.
=> Fix a typo about using incorrect component in the sample

CHANGELOG.md, src/bunit.web/TestDoubles/NavigationManager/FakeNavigationManager.cs, tests/bunit.web.tests/TestDoubles/NavigationManager/FakeNavigationManagerTest.cs
Fixes #458 
In theory this is a API breaking change as Uri is different before than after the change.
=> Use AbsoluteUri in FakeNavigationManager to preserve escpaed uri's

CHANGELOG.md, src/bunit.web/EventDispatchExtensions/MouseEventDispatchExtensions.cs, tests/bunit.web.tests/EventDispatchExtensions/EventDispatchExtensionsTest.cs, tests/bunit.web.tests/EventDispatchExtensions/MouseEventDispatchExtensionsTest.cs
=> fix: Click and DoubleClick methods have correct detail default set.

docs/site/docs/verification/semantic-html-comparison.md
Added diff:ignoreChildren and diff:ignoreAttributes missed description in docs.
I closed the PR #571, and opened this one.
Adjusted the text so it is more obvious that ignoreChildren only ignores children and not attributes. Same with the ignoreAttributes modifier.
Also added a note that attributes can be combined.
=> ADD: diff:ignoreChildren and diff:ignoreAttributes description to docs

CHANGELOG.md, src/bunit.web/EventDispatchExtensions/MouseEventDispatchExtensions.cs
This PR adds the following new properties to the `Click` and `DoubleClick` extension method:
* `OffsetX` and `OffsetY` for net5 and net6
* `PageX` and `PageY` for net6
If targeted against netstandard2.1there is no difference.
=> feat: Added additional introduced flags in MouseEventArgs (net5 or higher)

docs/site/docs/getting-started/create-test-project.md
Updates documentation regarding the use of bUnit template for creating test projects that target xUnit, NUnit or MSTest testing framework.
refs: #129, #625
=> docs: Update test project template usage (#129)

.github/workflows/verification.yml, CHANGELOG.md, src/bunit.template/template/.template.config/dotnetcli.host.json, src/bunit.template/template/.template.config/template.json, src/bunit.template/template/BunitTestContext.cs, src/bunit.template/template/Company.BlazorTests1.csproj, src/bunit.template/template/CounterCSharpTests.cs, src/bunit.template/template/CounterRazorTests.razor, src/bunit.template/template/_Imports.razor
Add support for MSTest and NUnit test framweworks in bUnit test template
refs: #129
- Please pay extra attention to the changes in `verification.yml` since I didn't have the chance to actually run the workflow (and am not too familiar with it).
- The documentation relies on using the `TestContextWrapper` to initialize the test classes in NUnit and MSTest frameworks. I've found a different way of achieving the goal by using global usings in combination with an alias. My reasons for doing this are the following:
- Templates are identical (except specific test attributes) across different test frameworks
- Test setup is (arguably) cleaner
That being said, if you believe this should be reverted, I have no issues with …
=> feat: Support multiple test frameworks in bUnit test template (#129)

src/Directory.Build.props, src/bunit.core/bunit.core.csproj, src/bunit.template/bunit.template.csproj, src/bunit.web.testcomponents/bunit.web.testcomponents.csproj, src/bunit.web/bunit.web.csproj, src/bunit/bunit.csproj
Just a smaller quality of life PR:
GitVersion nuget package was used in every src project so it made sense to move it up to the `Directory.Builds.props`.
If merged, closes #699 as I already use the new version.
=> refactor: GitVersion in Directory.Build.props

CHANGELOG.md, src/bunit.web/Rendering/Internal/Htmlizer.cs
The PR replaces the current `List<string>` with a `StringBuilder`.  This brings mainly 3 advantages:
* Make the intent better visible
* Less allocations
* Better performance
I know the original implementation comes from @SteveSandersonMS, but not sure what the motivation was.
Anyway I thought I take the lead and propose a different approach with the given advantages on the top.
Feedback very welcome.
The test just renders a rather small component. The results will be even better when we render bigger components.
For the test I used the `MultipleChildContent` as reference. 
```csharp
|          Method |     Mean |   Error |   StdDev |   Gen 0 |   Gen 1 | Allocated |
|---------------- |---------:|--------:|---------:|--------:|--------:|----------:|
| RenderComponent | 388.9 us | 7.72 us | …
```
=> refactor: use StringBuilder instead of List

.github/workflows/release-preview.yml
Only run `release-preview` when triggered from `main`.
=> refactor: check if main branch

src/bunit.web.testcomponents/bunit.web.testcomponents.csproj, tests/bunit.web.testcomponents.tests/RazorTesting/RazorTestDiscovererTest.cs, tests/bunit.web.testcomponents.tests/RazorTesting/RazorTestSourceInformationProviderTest.cs, tests/bunit.web.testcomponents.tests/SampleComponents/MixedCaseComponent.rAzOr, tests/bunit.web.testcomponents.tests/bunit.web.testcomponents.tests.csproj
I dont want to support net7 for test components, so that is removed. Unfortunately they are on nuget with .net6 target framework, so I updated the test project to also test for .net6.
This should also fix the failing nightly-builds with net7.
=> fix: dont support net7 for deprecated testcomponents

docs/site/docs/external-resources.md, docs/site/docs/getting-started/index.md
I added 3 new entries:
* A book in the new book section
* Your talk about new .net6 content in bUnit
* Stackoverflow as another source where people may find valuable resources
=> add: .net6 bUnit youtube video plus books and SO

CHANGELOG.md, src/bunit.core/Extensions/WaitForHelpers/WaitForHelper.cs, src/bunit.core/Extensions/WaitForHelpers/WaitForHelperLoggerExtensions.cs, src/bunit.core/Rendering/TestRenderer.cs, tests/bunit.core.tests/Extensions/WaitForHelpers/RenderedFragmentWaitForHelperExtensionsTest.cs, tests/bunit.core.tests/TestContextBaseTest.net5.cs, tests/bunit.testassets/AssertExtensions/TaskAssertionExtensions.cs, tests/bunit.web.tests/BlazorE2E/ComponentRenderingTest.cs, tests/bunit.web.tests/Extensions/WaitForHelpers/RenderedFragmentWaitForElementsHelperExtensionsTest.cs
Fixed #577.
THIS is experimental.
My idea was to, instead of using a lock around the the render tree getting build and find component's traversing the render tree to find components, is to just run the find component logic inside the dispatcher for the renderer. That should ensure that only at the time is allowed to happen.
=> fix: deadlock between FindComponents and updates of rendered components

.github/workflows/verification.yml
updates to verification workflow with dump collection, targeting os x as well, and include ability to cancel previous runs when new commits are pushed.
fixes #733
Todo:
Inspiration: https://yonatankra.com/7-github-actions-tricks-i-wish-i-knew-before-i-started/
=> build: enable osx, run template tests on windows also

.github/backmerge_failed.md, .github/workflows/backmerge-to-v2.yml
This PR adds a GitHub workflow which automatically merges changes from `main` to `v2` when there are changes on `main`.
If the merge is not successful an issue is created.
=> add: Automatically backmerge to v2 on push to main

docs/samples/tests/razor/TwoWayBindingTest.razor, docs/site/docs/providing-input/passing-parameters-to-components.md
This is a small follow-up to #750 and addresses partially #761.
Basically our shown example derived directly from `ComponentBase` which would lead to errors for the user.
The updated documentation will show a warning when checking the razor file for `@bind`.
=> fix: Fixed sample in docs and added more details

docs/site/docs/providing-input/substituting-components.md
While I was running through the docs I saw some super small issues.
Basically the opening tag of the `<div>` was missing which would result in a compilation error for the user if he just copy pastes that thing.
=> fix: Added missing opening tag

.github/workflows/verification-dotnet-nightly.yml, .github/workflows/verification.yml
Found the issue with the workflow:
```yml
- name: Run unit tests
run: |
dotnet test ./tests/ProjectA/ProjectA.csproj -c release
dotnet test ./tests/ProjectB/ProjectB.csproj -c release
dotnet test ./tests/ProjectC/ProjectC.csproj -c release
```
Let's assume ProjectA or ProjectB do have a test, which fails. Therefore the exit code is non-zero but ProjectC is successful the whole result code (in powershell) is for some weird reason 0 instead of non-zero.
So this is a temporary fix. Disadvantage right now is that we stop on the first failing test-suite **but** at least we have an indication whether or not windows is breaking.
=> Windows runner

.github/workflows/verification-dotnet-nightly.yml
The night-verification forces net7.0 as target configuration. On `main` we unfortunately have projects which don't support `net7.0` as configuration and are therefore failing.
I reverted the nightly verification back to "normal". 
As it is running on a ubuntu machine we shouldn't expect that windows error anyway.
Once we go "live" with `v2` we can simplify this again.
=> fix: Reverted change for net7.0 nightly verification

src/bunit.core/ComponentParameterCollectionBuilder.cs, tests/bunit.core.tests/ComponentParameterCollectionBuilderTests.cs, tests/bunit.core.tests/ShouldlyExtensions.cs
Small cleanup. We used in some places the `AllowNullAtrribute` which I replaced with the nullable reference type annotation.
I did this on `v2` as it is a breaking change itself.
=> refactor: use nullable type instead of annotation

tests/bunit.web.tests/JSInterop/BunitJSInteropTest.cs, tests/bunit.web.tests/JSInterop/BunitJSObjectReferenceTest.cs
=> fix: Allow obsolete InvokeUnmarshalled method

src/bunit.web/TestDoubles/Authorization/FakeAuthorizationExtensions.cs, src/bunit.web/TestDoubles/NavigationManager/FakeSignOutSessionStateManager.cs, tests/bunit.testassets/SampleComponents/SignOutSessionManagerLoginDisplay.razor
Fixes #836 
Even though the dotnet team wants to use the `NavigationManager` for logout, we still want to support the `SignOutSessionManager` until it is removed from the framework itself.
=> fix: Allow obsolete SignOutSessionManager for net7

.github/backmerge-failed.md, .github/workflows/docs-deploy.yml, .github/workflows/release-preview.yml, .github/workflows/release.yml, .github/workflows/verification.yml
Small update to resolve the often times occuring **ECONNRESET** (see here:https://github.com/actions/setup-dotnet/releases/tag/v3.0.3)
Here in action: https://github.com/bUnit-dev/bUnit/actions/runs/3367681380/jobs/5585393814
=> chore: Update setup-action

.github/workflows/verification.yml, tests/bunit.testassets/AssertExtensions/TaskAssertionExtensions.cs
Use the `WaitAsync` logic for `net6.0` and above otherwise, we use a "better" handling, which closes the `Task.Delay` via a `CancellationToken`.
=> refactor: Use WaitAsync logic for >net6.0

src/bunit.core/Extensions/WaitForHelpers/RenderedFragmentWaitForHelperExtensions.cs, src/bunit.core/Rendering/RootRenderTree.cs, src/bunit.core/StringSyntaxAttribute.cs, src/bunit.web/Asserting/DiffAssertExtensions.cs, src/bunit.web/Extensions/WaitForHelpers/RenderedFragmentWaitForHelperExtensions.cs, src/bunit.web/JSInterop/JSRuntimeInvocationDictionary.cs, src/bunit.web/TestDoubles/Authorization/FakeAuthorizationService.cs, tests/bunit.core.tests/ComponentFactories/GenericComponentFactoryTest.cs, tests/bunit.core.tests/ComponentParameterCollectionBuilderTests.cs, tests/bunit.core.tests/ComponentParameterCollectionTest.cs, tests/bunit.core.tests/ComponentParameterFactoryTest.cs, tests/bunit.core.tests/Extensions/WaitForHelpers/RenderedFragmentWaitForHelperExtensionsTest.cs, tests/bunit.core.tests/Rendering/RootRenderTreeTest.cs, tests/bunit.core.tests/Rendering/TestRendererTest.cs, tests/bunit.core.tests/TestServiceProviderTest.cs, tests/bunit.testassets/AssertExtensions/TaskAssertionExtensions.cs, tests/bunit.testassets/Serilog.Sinks.XUnit/TestOutputSink.cs, tests/bunit.testassets/ServiceCollectionLoggingExtensions.cs, tests/bunit.web.testcomponents.tests/RazorTesting/FixtureBaseTest.cs, tests/bunit.web.tests/ComponentFactories/StubComponentFactoryTest.cs, tests/bunit.web.tests/Extensions/InputFile/InputFileTests.cs, tests/bunit.web.tests/Extensions/RefreshingWrappedElementTest.cs, tests/bunit.web.tests/JSInterop/InvocationHandlers/FocusAsyncInvocationHandlerTest.cs, tests/bunit.web.tests/JSInterop/InvocationHandlers/FocusOnNavigateHandlerTest.cs, tests/bunit.web.tests/Rendering/Internal/HtmlizerTests.cs, tests/bunit.web.tests/TestContextTest.cs, tests/bunit.web.tests/TestDoubles/Components/ComponentDoubleBaseTest.cs, tests/bunit.web.tests/TestDoubles/NavigationManager/FakeNavigationManagerTest.cs
This PR was meant to fix some of the new analyzers shipped with `net7.0` that got activated with `7.0.1`.
* Made internal/private types sealed
* When `IEnumerable` was enumerated multiple times, I created a `List`
* Simplified some exception handling
* Simplified some `foreach` loops
=> refactor: Implemented analyzer suggestions and smaller refactorings

src/bunit.core/Rendering/TestRenderer.cs
I do think we should cancel the underlying Task for the unhandled exception in our `TestRenderer`.
=> fix: Cancel ExceptionTsc on dispose

.github/workflows/prepare-release.yml
Use the correct syntax for storing into env variables.
See: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
=> fix: Use correct syntax for env variables

CHANGELOG.md, src/bunit.web/TestDoubles/NavigationManager/FakeNavigationManager.cs, tests/bunit.web.tests/TestDoubles/NavigationManager/FakeNavigationManagerTest.cs
Fix FakeNavigationManager when navigating to Uri without absolute path.
I run some unit tests of a component today that navigates without problem to a path without absolute path.
But in unit test it throws. I did some unit test of bUnit and found out that FakeNavigationManager could not handle that case.
So this is a PR, that seems to fix it. 
=> Fix FakeNavigationManager when navigating to Uri without absolute path.

CHANGELOG.md, src/bunit.web/Rendering/Internal/Htmlizer.cs, tests/bunit.testassets/BlazorE2E/ComponentWithEscapableCharacters.razor, tests/bunit.web.tests/BlazorE2E/ComponentRenderingTest.cs
This PR fixes #947 and fixes #946
=> fix: Escape certain characters for attribute values

CHANGELOG.md, src/bunit.web/Extensions/TestServiceProviderExtensions.cs, src/bunit.web/bunit.web.csproj
This PR closes #954 
By default, the container has an `IMemoryCache` implementation available. This aligns the behavior to what ASP.NET Core does.
=> feat: Added IMemoryCache by default to the container

src/AngleSharpWrappers/AngleSharpWrappers.csproj, src/bunit.web/bunit.web.csproj
Remove obsolete `AngleSharp.CSS` dependency.
This closes #958
=> chore: Remove AngleSharp.CSS

CHANGELOG.md, src/bunit.web/Diffing/BlazorDiffingHelpers.cs, src/bunit.web/Diffing/HtmlComparer.cs, tests/bunit.testassets/SampleComponents/SimpleSvg.razor, tests/bunit.testassets/XunitExtensions/TheoryDataExtensions.cs, tests/bunit.web.tests/Asserting/MarkupMatchesAssertExtensionsTest.cs, tests/bunit.web.tests/Rendering/BunitHtmlParserTest.cs
Changed semantic comparer to handle elements parsed outside their proper context, e.g. an `<path>` element parsed without being inside a `<svg>` element. The semantic comparer will now be able to treat those as regular elements and thus be able to compare correctly to other elements of the same type and with the same node name.
Motivation: https://stackoverflow.com/questions/75335821/bunit-simple-markup-verification-for-path-tag
=> fix: allow semantic comparer to compare IHtmlUnknownElement types

CHANGELOG.md, src/bunit.web/EventDispatchExtensions/TriggerEventDispatchExtensions.cs, tests/bunit.testassets/SampleComponents/SubmitFormOnClick.razor, tests/bunit.web.tests/EventDispatchExtensions/GeneralEventDispatchExtensionsTest.cs
=> Honor preventdefault for events so they don't bubble

CHANGELOG.md, src/bunit.web/EventDispatchExtensions/TriggerEventDispatchExtensions.cs, tests/bunit.testassets/SampleComponents/ButtonsInsideForm.razor, tests/bunit.testassets/SampleComponents/SubmitFormOnClick.razor, tests/bunit.web.tests/EventDispatchExtensions/GeneralEventDispatchExtensionsTest.cs
=> fix: submit button/input element submits form

src/bunit.core/Rendering/RootRenderTree.cs, src/bunit.core/Rendering/TestRenderer.cs
Tiny PR with two refactorings:
* Simplify `GetCountOf` to use LINQ query - yes that would be a small performance regression - but no one on GitHub is using this function anyway (https://grep.app/search?q=.GetCountOf&filter[lang][0]=C%23)
* Small early return if the lookup is successful
=> refactor: use early return and simplify call

src/bunit.web/TestContext.cs
Nullability should reflect facts.
=> fix(nullable): forward nullability correctly

.editorconfig, CHANGELOG.md, Directory.Build.props, src/bunit.core/Extensions/WaitForHelpers/WaitForFailedException.cs, src/bunit.core/Rendering/RootComponent.cs, src/bunit.core/Rendering/TestRenderer.cs, src/bunit.core/TestServiceProvider.cs, src/bunit.web/Extensions/TestServiceProviderExtensions.cs, tests/.editorconfig, tests/AngleSharpWrappers.Tests/ElementWrapperTest.cs, tests/AngleSharpWrappers.Tests/HtmlParser.cs, tests/AngleSharpWrappers.Tests/TestFactory.cs, tests/bunit.testassets/XunitExtensions/RepeatAttribute.cs, tests/bunit.testassets/XunitExtensions/TheoryDataExtensions.cs, tests/bunit.web.testcomponents.tests/RazorTesting/RazorTestDiscovererTest.cs, tests/bunit.web.tests/BlazorE2E/ComponentRenderingTest.cs, tests/bunit.web.tests/EventDispatchExtensions/GeneralEventDispatchExtensionsTest.cs, tests/bunit.web.tests/Extensions/WaitForHelpers/RenderedFragmentWaitForElementsHelperExtensions.Async.Test.cs, tests/bunit.web.tests/Extensions/WaitForHelpers/RenderedFragmentWaitForElementsHelperExtensionsTest.cs, tests/bunit.web.tests/Rendering/BunitHtmlParserTest.cs, tests/bunit.web.tests/TestDoubles/Authorization/AuthorizationTest.cs
Changed test renderer such that updates to rendered components markup happen in the same synchronization context as the test framework is using (if any).
This includes two changes:
1. a lock around calls to `base.ProcessPendingRender()` and
2. using the callers sync context to update rendered components/rendered fragments DOM
The theory is that multiple async renders (calls to StateHasChanged)
that happen rapidly can cause the internal render tree to get
updated almost concurrently. The updates to the render tree
happens after calling base.ProcessPendingRender() and is finished
when UpdateDisplayAsync is called.
Since UpdateDisplayAsync is used to notify RenderedComponent/RenderedFragment
to update their markup based on render tree data retrieved via
Renderer.GetCurrentRenderTreeFrames, …
=> Fix: run dom update in test sync context

MIGRATION.md, src/bunit.core/Extensions/LoggerHelperExtensions.cs, src/bunit.web/Extensions/EnumerableExtensions.cs
I moved the `EnumerableExtensions` to `bunit.web` and made it `internal`.
There are two reasons: The main point being that this is a very common extension people are using - this might confuse users as well as conflict with other 3rd party libraries. I don't think bUnit should expose such functions.
The second reason: We are only using it in one place - I was thinking even having it only has a static local function instead of an extension.
=> V2 enumerable internal

.editorconfig, MIGRATION.md, src/bunit/Asserting/ActualExpectedAssertException.cs, src/bunit/Asserting/HtmlEqualException.cs, src/bunit/Asserting/JSInvokeCountExpectedException.cs, src/bunit/EventDispatchExtensions/MissingEventHandlerException.cs, src/bunit/Extensions/ElementNotFoundException.cs, src/bunit/Extensions/ElementRemovedFromDomException.cs, src/bunit/Extensions/TestServiceProviderExtensions.cs, src/bunit/Extensions/WaitForHelpers/WaitForFailedException.cs, src/bunit/JSInterop/JSRuntimeUnhandledInvocationException.cs, src/bunit/ParameterException.cs, src/bunit/Rendering/ComponentDisposedException.cs, src/bunit/Rendering/ComponentNotFoundException.cs, src/bunit/Rendering/TestRenderer.cs, src/bunit/Rendering/UnknownEventHandlerIdException.cs, src/bunit/TestDoubles/Authorization/MissingFakeAuthorizationException.cs, src/bunit/TestDoubles/Components/ParameterNotFoundException.cs, src/bunit/TestDoubles/HttpClient/MissingMockHttpClientException.cs, src/bunit/TestDoubles/Localization/MissingMockStringLocalizationException.cs, src/bunit/TestDoubles/ScrollToLocationHash/FakeScrollToLocationHash.cs, src/bunit/TestServiceProvider.cs, tests/bunit.tests/JSInterop/InvocationHandlers/FocusOnNavigateHandlerTest.cs, tests/bunit.tests/TestServiceProviderTest.cs
Renamed the function from `Add` to `Set` as the user is not able to have a list of fallback providers, but only one.
The API naming makes it clearer.
=> refactor: Rename fallback service provider method

CHANGELOG.md, src/bunit.core/Extensions/WaitForHelpers/WaitForHelper.cs, src/bunit.core/Rendering/TestRenderer.cs, src/bunit.core/Rendering/TestRendererLoggerExtensions.cs, src/bunit.core/TestContextBase.cs, tests/Directory.Build.props, tests/bunit.core.tests/Rendering/TestRendererTest.cs, tests/bunit.testassets/bunit.testassets.csproj, tests/bunit.web.testcomponents.tests/bunit.web.testcomponents.tests.csproj, tests/bunit.web.tests/BlazorE2E/ComponentRenderingTest.cs, tests/bunit.web.tests/EventDispatchExtensions/GeneralEventDispatchExtensionsTest.cs, tests/bunit.web.tests/Extensions/WaitForHelpers/RenderedFragmentWaitForElementsHelperExtensions.Async.Test.cs, tests/bunit.web.tests/Extensions/WaitForHelpers/RenderedFragmentWaitForElementsHelperExtensionsTest.cs, tests/bunit.web.tests/TestDoubles/Authorization/AuthorizationTest.cs
To prevent access to the Renderer's internal render tree after it has or is in the process of being disposed, we use the render tree lock to sync access during disposal.
The change here also stops an in-progress render if Dipose has been called, and throws ObjectDisposedException if the user tries to access the render tree after disposable or tries to call the Render method.
This could be a fix for https://github.com/bUnit-dev/bUnit/issues/1064
Update: When running our own test locally on my slow laptop, sometimes our test will fail due to the timeout being hit before the number of expected render cycles has happened. Thus I have also provided a way for us and users to override the default timeout of 1 second to enable us to more easily set another default in multiple tests.
=> Block access renderer's methods and stop rendering after dispose

src/bunit/TestDoubles/NavigationManager/FakeNavigationManager.cs, src/bunit/TestDoubles/NavigationManager/NavigationHistory.cs
This PR is related to #1077 and starts to add some crucial information for the `FakeNavigationManager` and its types.
Result:
=> feat: Added Debugger hints for FakeNavigationManager types

MIGRATION.md, docs/samples/tests/xunit/FallBackServiceProviderUsage.cs, docs/samples/tests/xunit/InjectAuthServiceTest.cs, docs/samples/tests/xunit/UserInfoTest.cs, docs/samples/tests/xunit/UserRightsTest.cs, docs/site/docs/test-doubles/auth.md, docs/site/docs/test-doubles/persistentcomponentstate.md, src/bunit/TestContextBase.cs, src/bunit/TestDoubles/Authorization/BunitAuthorizationContext.cs, src/bunit/TestDoubles/Authorization/BunitAuthorizationExtensions.cs, src/bunit/TestDoubles/PersistentComponentState/TestContextBaseExtensions.cs, tests/bunit.tests/TestDoubles/Authorization/AuthorizationTest.cs, tests/bunit.tests/TestDoubles/Authorization/TestAuthorizationContextTest.cs, tests/bunit.tests/TestDoubles/BunitSignOutSessionStateManagerTest.cs, tests/bunit.tests/TestDoubles/PersistentComponentState/BunitPersistentComponentStateTest.cs
This PR closes #1081 
This PR removed the necessity to call `this.` for:
* AddBunitPersistentComponentState
* AddTestAuthorization
=> refactor: remove extensions in favor of partial class

src/bunit/ComponentParameter.cs, src/bunit/Extensions/InputFile/BunitBrowserFile.cs, src/bunit/Extensions/InputFile/InputFileExtensions.cs, src/bunit/Extensions/Internal/RefreshableElementCollection.cs, src/bunit/ParameterException.cs, tests/bunit.tests/Rendering/ComponentParameterTest.cs
This PR does the following:
* Add another enhanced debugger tip for `RefreshableElementCollection`
* Renamed `BUnitBrowserFile` to `BunitBrowserFile`
* Made `ComponentParameter` a `record struct` to simplify some code.
This PR enhances #1077
=> More debugger hints

src/bunit/Rendering/RenderedFragment.cs
We should unsubscribe from all events in the `Dispose` method.
Furthermore, for `v2`: We should (in the docs as well as in our code base) use the `using` more often. 
From:
```csharp
var cut = RenderComponent<MyComponent>();
```
To:
```csharp
using var cut = RenderComponent<MyComponent>();
```
The reason is that I found multiple instances where we are still attached via `OnMarkupUpdated` event, hindering the GC from doing its work. Of course, for calls to `FindComponent` that isn't necessary as there is no active subscriber to those events.
=> Markup event dispose

tests/bunit.testassets/BlazorE2E/KeyPressEventComponent.razor
You asked yourself, where this:
```json
{"Key":"a","Code":null,"Location":0,"Repeat":false,"CtrlKey":false,"ShiftKey":false,"AltKey":false,"MetaKey":false,"Type":null}
{"Key":"b","Code":null,"Location":0,"Repeat":false,"CtrlKey":false,"ShiftKey":false,"AltKey":false,"MetaKey":false,"Type":null}
```
Is coming from? There we go ;) as we use the console directly - it will just pop up once a test fails (due to Debug log level(
=> refactor: Remove Console logging

src/bunit/JSInterop/JSRuntimeInvocationDictionary.cs, src/bunit/TestDoubles/Components/CapturedParameterView{TComponent}.cs, tests/.editorconfig
I got a local error (in Release):
```no-class
/Users/stgi/repos/bUnit/src/bunit/TestDoubles/Components/CapturedParameterView{TComponent}.cs(104,10): error CS8620: Argument of type 'IReadOnlyDictionary<string, object?>' cannot be used for parameter 'parameters' of type 'IReadOnlyDictionary<string, object>' in 'CapturedParameterView<TComponent>.CapturedParameterView(IReadOnlyDictionary<string, object> parameters)' due to differences in the nullability of reference types. [/Users/stgi/repos/bUnit/src/bunit/bunit.csproj]
0 Warning(s)
1 Error(s)
```
Therefore here the fix. Not sure why our CI/CD pipeline was quite.
=> fix: use correct nullability annotation in type

src/bunit/Rendering/BunitRenderer.cs, tests/bunit.tests/Rendering/BunitRendererTest.cs
The current implementation just creates the instance without any side-effects of those new attributes.
I don't see any reason why someone should unit test that anyway.
=> feat: Add support for RenderModeAttribute

src/bunit.core/Rendering/TestRenderer.cs
Look at the logs that @groogiam has shared with me, I see a bunch of renders happening after the TestRenderer has been disposed, i.e. LogRenderCycleActiveAfterDispose is being triggered.
However, that does not explain the stack overflow. Thus, the following code should prevent loading render tree frames from being loaded in an endless loop, perhaps because were are attempting load render tree frames for disposed components.
fixes #1064
=> fix: prevent endless recursion loading render tree frames

.github/workflows/verification.yml, CHANGELOG.md, benchmark/bunit.benchmarks/BenchmarkBase.cs, src/bunit.core/TestContextBase.cs, src/bunit.core/TestDoubles/PersistentComponentState/TestContextBaseExtensions.cs, src/bunit.core/TestServiceProvider.cs, src/bunit.web.testcomponents/Xunit.Sdk/RazorTestInvoker.cs, src/bunit.web/Extensions/TestServiceProviderExtensions.cs, src/bunit.web/TestDoubles/Authorization/FakeAuthorizationExtensions.cs, src/bunit.web/TestDoubles/Authorization/TestAuthorizationContext.cs, tests/bunit.core.tests/Rendering/BunitComponentActivatorTest.cs
=> fix: Change all bUnit services registration from singleton to scoped

CHANGELOG.md, src/bunit.template/template/.template.config/dotnetcli.host.json, src/bunit.template/template/.template.config/template.json, src/bunit.template/template/Company.BlazorTests1.csproj
This Pull Request does the following additions / changes:
* Added the target SDK as optional parameter when creating the bUnit project
* It currently targets `net6.0` as this is the current LTS. I thought about scripting this away, but it seems way easier to bump our default every 2 years and remove obsolete versions and set the default to the current LTS
* I updated the dependencies to the latest state
* Fixed an issue with h2/h3 in the changelog.md 
This tackles partially #1093
=> feat: Add target sdk for template

src/bunit.core/Extensions/WaitForHelpers/WaitForHelperLoggerExtensions.cs, src/bunit.core/Rendering/RenderEvent.cs, src/bunit.core/Rendering/TestRenderer.cs, src/bunit.core/Rendering/TestRendererLoggerExtensions.cs, src/bunit.web/TestDoubles/ErrorBoundary/BunitErrorBoundaryLogger.cs, tests/Directory.Build.props, tests/bunit.core.tests/Rendering/TestRendererTest.cs, tests/bunit.testassets/ServiceCollectionLoggingExtensions.cs, tests/bunit.testassets/bunit.testassets.csproj, tests/bunit.web.testcomponents.tests/bunit.web.testcomponents.tests.csproj, tests/bunit.web.tests/EventDispatchExtensions/ClipboardEventDispatchExtensionsTest.cs, tests/bunit.web.tests/EventDispatchExtensions/DetailsElementEventDispatcherExtensionsTest.cs, tests/bunit.web.tests/EventDispatchExtensions/DragEventDispatchExtensionsTest.cs, tests/bunit.web.tests/EventDispatchExtensions/EventDispatchExtensionsTest.cs, tests/bunit.web.tests/EventDispatchExtensions/FocusEventDispatchExtensionsTest.cs, tests/bunit.web.tests/EventDispatchExtensions/GeneralEventDispatchExtensionsTest.cs, tests/bunit.web.tests/EventDispatchExtensions/InputEventDispatchExtensionsTest.cs, tests/bunit.web.tests/EventDispatchExtensions/KeyboardEventDispatchExtensionsTest.cs, tests/bunit.web.tests/EventDispatchExtensions/MediaEventDispatchExtensionsTest.cs, tests/bunit.web.tests/EventDispatchExtensions/MouseEventDispatchExtensionsTest.cs, tests/bunit.web.tests/EventDispatchExtensions/PointerEventDispatchExtensionsTest.cs, tests/bunit.web.tests/EventDispatchExtensions/ProgressEventDispatchExtensionsTest.cs, tests/bunit.web.tests/EventDispatchExtensions/TouchEventDispatchExtensionsTest.cs, tests/bunit.web.tests/EventDispatchExtensions/WheelEventDispatchExtensionsTest.cs
The second round of changes that should prevent stack overflow reported in #1064.
I will attempt to push a preview release directly from this branch so we can test it before going further.
=> Protecting the render tree

src/bunit.web/Rendering/WebTestRenderer.cs, tests/bunit.testassets/SampleComponents/LoadingComponent.razor, tests/bunit.web.tests/Asserting/MarkupMatchesTests.razor
=> fix: Use NullDispatchTestRenderer for detached rendering

src/bunit.web/Asserting/MarkupMatchesAssertExtensions.cs, tests/.editorconfig, tests/bunit.testassets/SampleComponents/InvokeAsyncInsideContinueWith.razor, tests/bunit.web.tests/Asserting/MarkupMatchesTests.razor
Newing up a renderer for `MarkupMatches` to prevent being deadlocked to renderer the expected `RenderFragment`.
=> fix: New up renderer for markup matches

.github/workflows/docs-deploy.yml, .github/workflows/release-preview.yml, .github/workflows/release.yml, .github/workflows/verification.yml, CHANGELOG.md, Directory.Build.props, global.json, src/bunit.core/Rendering/TestRenderer.cs, src/bunit.core/bunit.core.csproj, src/bunit.web.testcomponents/bunit.web.testcomponents.csproj, src/bunit.web/Asserting/JSInvokeCountExpectedException.cs, src/bunit.web/Extensions/ElementNotFoundException.cs, src/bunit.web/Extensions/TestServiceProviderExtensions.cs, src/bunit.web/JSInterop/JSRuntimeInvocationDictionary.cs, src/bunit.web/Rendering/RenderedComponent.cs, src/bunit.web/TestDoubles/Components/CapturedParameterView{TComponent}.cs, src/bunit.web/TestDoubles/Localization/MissingMockStringLocalizationException.cs, src/bunit.web/TestDoubles/ScrollToLocationHash/BunitScrollToLocationHash.cs, src/bunit.web/bunit.web.csproj, src/bunit/bunit.csproj, tests/AngleSharpWrappers.Tests/AngleSharpWrappers.Tests.csproj, tests/bunit.core.tests/Rendering/TestRendererTest.cs, tests/bunit.core.tests/bunit.core.tests.csproj, tests/bunit.testassets/bunit.testassets.csproj, tests/bunit.web.tests/bunit.web.tests.csproj
This PR enables `net8.0` support for v1 of bunit.
This closes #1165
=> feat: Add support for net8.0

src/bunit/EventDispatchExtensions/Key.cs, src/bunit/JSInterop/JSRuntimeInvocation.cs, src/bunit/Rendering/BunitRenderer.cs
Small PR that uses `record` types where we implemented `IEquatable` earlier.
=> refactor: Use record instead of implementing ourselves

tests/Directory.Build.props, tests/bunit.core.tests/ComponentFactories/ConditionalComponentFactoryTest.cs, tests/bunit.core.tests/ComponentFactories/InstanceComponentFactoryTest.cs, tests/bunit.core.tests/ComponentFactories/TypeBasedComponentFactoryTest.cs, tests/bunit.core.tests/Rendering/TestRendererTest.net5.cs, tests/bunit.core.tests/TestContextBaseTest.net5.cs, tests/bunit.web.testcomponents.tests/RazorTesting/RazorTestDiscovererTest.cs, tests/bunit.web.testcomponents.tests/RazorTesting/RazorTestSourceInformationProviderTest.cs, tests/bunit.web.tests/Asserting/CompareToDiffingExtensionsTest.cs, tests/bunit.web.tests/Asserting/DiffAssertExtensionsTest.cs, tests/bunit.web.tests/Asserting/JSRuntimeAssertExtensionsTest.cs, tests/bunit.web.tests/EventDispatchExtensions/GeneralEventDispatchExtensionsTest.cs, tests/bunit.web.tests/TestDoubles/FakeSignOutSessionStateManagerTest.cs, tests/bunit.web.tests/TestUtilities/MockingHelpers.cs
This PR removes Moq in favor of NSubstitute.
Closes #1174 
I did refrain from changing the docs as many people are still using Moq, so I am fine with having Moq there for the time being.
=> refactor: Move from moq to NSubstitute

CHANGELOG.md, docs/site/docs/interaction/awaiting-async-state.md, src/bunit.core/Extensions/WaitForHelpers/RenderedFragmentWaitForHelperExtensions.cs, src/bunit.core/Extensions/WaitForHelpers/WaitForAssertionHelper.cs, src/bunit.core/Extensions/WaitForHelpers/WaitForHelper.cs
=> feat: Increase timeout to 5 minutes if a debugger is attached

.github/workflows/release-preview.yml, CHANGELOG.md, Directory.Build.props, src/bunit.core/Extensions/RenderedComponentRenderExtensions.cs, src/bunit.core/Rendering/TestRenderer.cs, src/bunit.web.testcomponents/bunit.web.testcomponents.csproj, src/bunit.web/JSInterop/InvocationHandlers/Implementation/VirtualizeJSRuntimeInvocationHandler.cs, tests/Directory.Build.props, tests/bunit.core.tests/Rendering/TestRendererTest.cs, tests/bunit.web.testcomponents.tests/RazorTesting/RazorTestSourceInformationProviderTest.cs, tests/bunit.web.testcomponents.tests/bunit.web.testcomponents.tests.csproj, tests/bunit.web.tests/TestDoubles/Authorization/FakeAuthenticationStateProviderTest.cs, tests/bunit.web.tests/TestDoubles/Authorization/FakeAuthorizationPolicyProviderTest.cs
If the renderer was not idle when calling `SetParametersAndRender`, the method could return before the parameters were set and the component under test had finished rendering. This was a regression that happened in v1.21.9.
fixes #1188
=> Block until SetParametersAndRender / Render calls complete

.editorconfig, .github/workflows/verification.yml, Directory.Build.props, MIGRATION.md, src/bunit/Extensions/InputFile/InputFileExtensions.cs, src/bunit/Extensions/RenderedComponentRenderExtensions.cs, src/bunit/Extensions/RenderedFragmentExtensions.cs, src/bunit/Extensions/RenderedFragmentInvokeAsyncExtensions.cs, src/bunit/Extensions/WaitForHelpers/WaitForHelper.cs, src/bunit/JSInterop/JSRuntimeInvocationDictionary.cs, src/bunit/Rendering/BunitRenderer.cs, src/bunit/Rendering/RenderedFragment.cs, src/bunit/TestContext.cs, src/bunit/TestDoubles/Authorization/BunitAuthorizationContext.cs, src/bunit/TestDoubles/Authorization/BunitAuthorizationExtensions.cs, src/bunit/TestDoubles/NavigationManager/BunitNavigationManager.cs, tests/.editorconfig, tests/Directory.Build.props, tests/bunit.testassets/SampleComponents/AsyncComponent.razor, tests/bunit.testassets/SampleComponents/CustomPasteSample.razor.cs, tests/bunit.testassets/SampleComponents/DelayRemovedRenderFragment.razor, tests/bunit.testassets/SampleComponents/PrintCurrentUrl.razor, tests/bunit.tests/Extensions/WaitForHelpers/RenderedFragmentWaitForElementsHelperExtensionsTest.cs, tests/bunit.tests/Rendering/BunitRendererTest.cs, tests/bunit.tests/Rendering/DeterministicRenderTests.cs, tests/bunit.tests/TestContextTest.cs
I open this PR not because it is ready, but to have some asynchronous discussion about some aspects of the deterministic renderer. 
Some open points:
=> Deterministic renderer

Directory.Build.props, src/.editorconfig, src/bunit.core/Rendering/TestRenderer.cs
Use the UnsafeAccessorAttribute instead of reflection for .NET 8 code paths. More here: https://github.com/dotnet/runtime/issues/81741
=> refactor: use UnsafeAccessorAttribute instead of reflection for .NET 8

CHANGELOG.md, docs/samples/tests/xunit/CustomServiceProviderFactory.cs, docs/samples/tests/xunit/CustomServiceProviderFactoryUsage.cs, docs/samples/tests/xunit/bunit.docs.xunit.samples.csproj, docs/site/docs/providing-input/inject-services-into-components.md, src/bunit.core/TestContextBase.cs, src/bunit.core/TestServiceProvider.cs, tests/bunit.core.tests/TestServiceProviderTest.cs
ASP.NET Core / Blazor allows for custom containers via IServiceProviderFactory<TContainerBuilder>.
This pull request adds this ability to the TestServiceProvider of bUnit.
Two times requested, I also need this and you told that you would like to have that as PR ;-)
See:
https://github.com/bUnit-dev/bUnit/discussions/268
https://github.com/bUnit-dev/bUnit/discussions/213
=> Allow custom service providers like autofac

.config/dotnet-tools.json, .github/workflows/verification.yml, CHANGELOG.md, Directory.Build.props, benchmark/bunit.benchmarks/bunit.benchmarks.csproj, bunit.sln, global.json, src/bunit.web.query/bunit.web.query.csproj, tests/Directory.Build.props, tests/bunit.core.tests/bunit.core.tests.csproj, tests/bunit.testassets/bunit.testassets.csproj, tests/bunit.web.query.tests/bunit.web.query.tests.csproj, tests/bunit.web.tests/bunit.web.tests.csproj, version.json
This PR was created in response to a manual trigger of the [prepare-release workflow](https://github.com/bUnit-dev/bUnit/actions/runs/6869544615).
=> Release of new minor version v1.25

docs/site/docs/getting-started/writing-tests.md
Added missing `System` namespace.
See:
See also: https://bunit.dev/docs/getting-started/writing-tests.html
=> fix: Added missing namespace for doc reference

docs/site/docs/providing-input/passing-parameters-to-components.md
Adding IOE text when using razor syntax for tests.
=> docs: add section about InvaldOperationException when using razor tests

docs/site/docs/providing-input/passing-parameters-to-components.md
=> docs: Add limitation for rendering a RenderFragment

CHANGELOG.md, docs/samples/components/CalcWithLoading.razor, docs/samples/components/CalcWithReturnValue.razor, docs/samples/tests/xunit/ReRenderTest.cs, docs/site/docs/interaction/trigger-renders.md, src/bunit.core/Extensions/RenderedFragmentInvokeAsyncExtensions.cs
Closes #1296
Didn't include tests since there's essentially no logic changes here and the second overload already doesn't have any, but I can add them if wanted.
=> Add overloads to InvokeAsync with a return value

docs/site/docs/toc.md
=> docs: Fix wrong link marker

.github/workflows/ci.yml, CHANGELOG.md, src/bunit.core/TestServiceProvider.cs, tests/.editorconfig, tests/bunit.core.tests/TestServiceProviderTest.cs, tests/bunit.generators.tests/bunit.generators.tests.csproj
=> feat: Added support for keyed services

src/bunit.generators.internal/bunit.generators.internal.csproj, src/bunit.generators/bunit.generators.csproj, tests/bunit.generators.tests/bunit.generators.tests.csproj
#1406 doesn't update everything leading to build errors.
=> chore: Update Source Code generator libs

version.json
I really would go for "beta" (or even "preview" as we already have it and as the dotnet team does it) instead of "alpha".
Mainly because I don't believe we are that unstable, and secondly, it is easier for folks to try a beta than an alpha (alpha conveys a certain meaning).
PS: Settled on preview.
=> fix: Use preview instead of alpha tag

MIGRATION.md, docs/samples/components/AsyncDisposableComponent.razor, docs/samples/tests/xunit/DisposeComponentsTest.cs, docs/site/docs/interaction/dispose-components.md, src/bunit/BunitContext.cs, src/bunit/Rendering/BunitRenderer.cs, tests/bunit.testassets/AssertExtensions/TaskAssertionExtensions.cs, tests/bunit.tests/BunitContextTest.cs
This Pull Request tackles and closes #1232
The idea is to hook into the queue and "collect" the disposal tasks in our renderer. 
I would like your opinion on the API design. I went back and forth and settled on the current shape (with an optional boolean flag).
=> feat: Add flag to actively wait for async disposal

.github/workflows/ci.yml
=> ci: only target net8 when validating docs/running docs tests

.devcontainer/devcontainer.json, .devcontainer/post-install.sh, .gitignore, .vscode/tasks.json, CONTRIBUTING.md
This PR enables devcontainer support so that folks can easily contribute to bUnit. Every GitHub user automatically has 120 CPU hours for free, which allows most people to contribute easily (even when using higher-tier machines). 
Especially updating docs means installing/configuring docfx, which is automatically done.
There are also three pre-defined tasks:
* Serve Docs without building bUnit - for just smaller things where API references aren't important
* Serve Docs with building - to enable the "full" documentation, especially linking
* Running all unit tests in release mode
Many things like building or even running tests, does work out of the box (even though you can unfortunately only run all tests or none - MS please fix that!)
Here some nice screenshots to convince you!
=> feat: add devcontainer

CHANGELOG.md, Directory.Build.props, benchmark/bunit.benchmarks.assets/bunit.benchmarks.assets.csproj, docs/samples/tests/Directory.Build.props, docs/samples/tests/razor/bunit.docs.razor.samples.csproj, docs/samples/tests/xunit/bunit.docs.xunit.samples.csproj, src/bunit.template/template/Company.BlazorTests1.csproj, src/bunit.web/Extensions/InputFile/BUnitBrowserFile.cs, src/bunit.web/Extensions/InputFile/InputFileExtensions.cs, src/bunit.web/bunit.web.csproj, tests/Directory.Build.props, tests/bunit.core.tests/bunit.core.tests.csproj, tests/bunit.generators.tests/bunit.generators.tests.csproj, tests/bunit.testassets/SampleComponents/PersistentComponentStateSample.razor.cs, tests/bunit.testassets/_Imports.razor, tests/bunit.testassets/bunit.testassets.csproj, tests/bunit.web.query.tests/bunit.web.query.tests.csproj, tests/bunit.web.tests/Extensions/InputFile/InputFileTests.cs, tests/bunit.web.tests/bunit.web.tests.csproj
Fixes #1503 
And fixes some package versions
=> fix: Bunit browser file exc

.github/workflows/release.yml, CHANGELOG.md, Directory.Build.props, benchmark/bunit.benchmarks/bunit.benchmarks.csproj, src/Directory.Build.props, src/bunit.web/Extensions/InputFile/InputFileExtensions.cs, src/bunit.web/JSInterop/InvocationHandlers/Implementation/VirtualizeJSRuntimeInvocationHandler.cs, src/bunit.web/Rendering/BunitHtmlParser.cs, src/bunit.web/TestDoubles/Localization/PlaceholderStringLocalization.cs, tests/bunit.generators.tests/bunit.generators.tests.csproj, tests/bunit.testassets/XunitExtensions/RepeatAttribute.cs, tests/bunit.testassets/bunit.testassets.csproj, tests/bunit.web.tests/TestDoubles/NavigationManager/FakeNavigationManagerTest.cs
=> fix: Only throw bUnit created exceptions to the user

docs/site/docs/test-doubles/input-file.md
Added section about limitations for `UploadFiles`.
Closes #1521
=> docs: Added Limitation for UploadFiles

docs/site/docs/providing-input/passing-parameters-to-components.md
Fix heading not rendering correctly.
Separately the sentence doesn’t seem right, like something was accidentally deleted, but I’m not sure what it was. I can tweak that too if needed if you let me know what it is.
=> Fix heading

src/bunit.generators/Web.Stubs/AddStubMethodStubGenerator/AddStubGenerator.cs, src/bunit.generators/Web.Stubs/AttributeStubGenerator/ComponentStubAttributeGenerator.cs, src/bunit.generators/Web.Stubs/MemberRetriever.cs, tests/bunit.generators.tests/Web.Stub/AddStubGeneratorTests.cs, tests/bunit.generators.tests/Web.Stub/Components/ContainerComponent.cs
Closes #1570 
Let the generator also look through base types.
=> feat: Respect base properties

Directory.Packages.props, src/bunit.core/Rendering/BunitComponentActivator.cs, src/bunit.core/Rendering/TestRenderer.cs, tests/bunit.testassets/SampleComponents/ConstructorInjectionComponent.cs, tests/bunit.web.tests/Rendering/RenderedComponentTest.cs
Closes #1578 
Also fixes CVE in `System.Text.Json` via package bump.
=> feat: Enable constructor injection

Directory.Packages.props
`System.Text.Json` in Version `8.0.x` supports `netstandard2.1` - therefore there is no need to manage different version across target frameworks.
=> fix: Use one central version for System.Text.Json

.github/workflows/ci.yml, src/bunit.template/template/.template.config/template.json, src/bunit.template/template/Company.BlazorTests1.csproj
Update our templates to support `net9.0` and make net9.0 the default too.
=> chore: Update templates for .net9 and make .net9 default

Directory.Packages.props, src/Directory.Build.props
> Starting with .NET 8, Source Link for the following source control providers is included in the .NET SDK and enabled by default:
> 
> [GitHub](http://github.com/) or [GitHub Enterprise](https://enterprise.github.com/home)
> [Azure Repos](https://azure.microsoft.com/en-us/services/devops/repos) git repositories (formerly known as Visual Studio Team Services)
> [GitLab](https://gitlab.com/) 12.0+ (for older versions see [GitLab settings](https://github.com/dotnet/sourcelink?tab=readme-ov-file#gitlab))
> [Bitbucket](https://bitbucket.org/) 4.7+ (for older versions see [Bitbucket settings](https://github.com/dotnet/sourcelink?tab=readme-ov-file#bitbucket))
> If your project uses .NET SDK 8+ and is hosted by the above providers it does not need to reference any Source Link packages or set …
=> remove source link package reference not necessary

src/bunit.web/Diffing/DiffMarkupFormatter.cs, src/bunit.web/Extensions/NodePrintExtensions.cs
PrettyMarkupFormatter is not thread safe
https://github.com/VerifyTests/Verify.Bunit/issues/60
=> remove static uses of PrettyMarkupFormatter

CHANGELOG.md
Hi @egil
This PR was created because the [release workflow](https://github.com/bUnit-dev/bUnit/actions/runs/12319083236) failed to automatically merge stable into main.
=> Update main with changes in stable after v1.37.7 release

.github/workflows/ci.yml, CHANGELOG.md, src/bunit.template/template/.template.config/dotnetcli.host.json, src/bunit.template/template/.template.config/template.json, src/bunit.template/template/Company.BlazorTests1.csproj, src/bunit.template/template/CounterCSharpTests.cs, src/bunit.template/template/CounterRazorTests.razor, src/bunit.template/template/_Imports.razor
Added another template for `xunit.v3`.
=> feat: Add templates for xunit.v3

src/bunit.core/Asserting/ActualExpectedAssertException.cs, src/bunit.core/Extensions/WaitForHelpers/WaitForFailedException.cs, src/bunit.core/Internal/XUnitExceptions/IAssertionException.cs, src/bunit.core/Internal/XUnitExceptions/ITestTimeoutException.cs, src/bunit.core/ParameterException.cs, src/bunit.web/Extensions/ElementRemovedFromDomException.cs
This PR adds `xunit.v3` marker interfaces to bUnits custom exceptions.
=> feat: Add xunit v3 markers

.github/workflows/ci.yml, CHANGELOG.md, Directory.Packages.props, src/bunit.core/Asserting/ActualExpectedAssertException.cs, src/bunit.core/Extensions/WaitForHelpers/WaitForFailedException.cs, src/bunit.core/Internal/XUnitExceptions/IAssertionException.cs, src/bunit.core/Internal/XUnitExceptions/ITestTimeoutException.cs, src/bunit.core/ParameterException.cs, src/bunit.template/template/.template.config/dotnetcli.host.json, src/bunit.template/template/.template.config/template.json, src/bunit.template/template/Company.BlazorTests1.csproj, src/bunit.template/template/CounterCSharpTests.cs, src/bunit.template/template/CounterRazorTests.razor, src/bunit.template/template/_Imports.razor, src/bunit.web/Extensions/ElementRemovedFromDomException.cs, version.json
This PR was created in response to a manual trigger of the [prepare-release workflow](https://github.com/bUnit-dev/bUnit/actions/runs/12734578096).
=> Release of new minor version v1.38

Directory.Packages.props, tests/bunit.core.tests/Rendering/RenderModeTests.razor, tests/bunit.core.tests/TestDoubles/PersistentComponentState/FakePersistentComponentStateTest.cs, tests/bunit.testassets/BlazorE2E/AddRemoveChildComponents.razor, tests/bunit.testassets/BlazorE2E/DataDashComponent.razor, tests/bunit.testassets/BlazorE2E/DuplicateAttributesComponent.razor, tests/bunit.testassets/BlazorE2E/KeyPressEventComponent.razor, tests/bunit.testassets/BlazorE2E/MarkupBlockComponent.razor, tests/bunit.testassets/BlazorE2E/MovingCheckboxesComponent.razor, tests/bunit.testassets/BlazorE2E/OrderedList.razor, tests/bunit.testassets/SampleComponents/AsyncRenderChangesProperty.razor, tests/bunit.testassets/SampleComponents/InvokeAsyncInsideContinueWith.razor, tests/bunit.testassets/SampleComponents/RenderOnClick.razor, tests/bunit.testassets/SampleComponents/SimpleUsingLocalizer.razor, tests/bunit.testassets/SampleComponents/SimpleWithTemplate.razor, tests/bunit.testassets/SampleComponents/ToggleableDetails.razor, tests/bunit.web.tests/Asserting/MarkupMatchesTests.razor
Upgrading SonarAnalyzers.CSharp package
=> chore: Upgrade SA

docs/site/docs/verification/semantic-html-comparison.md
Adds the character `>` to the documentation to close the HTML-tag.
=> Add missing closing bracket in semantic-html-comparison.md

.github/workflows/ci.yml, .github/workflows/docs-deploy.yml, .github/workflows/release.yml, Directory.Packages.props, docs/samples/components/bunit.docs.samples.csproj, global.json, src/bunit.web.query/bunit.web.query.csproj, src/bunit/JSInterop/Implementation/BunitJSObjectReference.cs, src/bunit/JSInterop/Implementation/BunitJSRuntime.cs, src/bunit/bunit.csproj, tests/bunit.testassets/bunit.testassets.csproj, tests/bunit.tests/bunit.tests.csproj, tests/bunit.web.query.tests/bunit.web.query.tests.csproj
This PR makes bUnit `v2` **compilable** (as in, it compiles but doesn't support new features) against `net10.0`.
=> feat: Add net10

src/bunit/BunitContext.cs, src/bunit/JSInterop/InvocationHandlers/JSRuntimeInvocationHandlerBase{TResult}.cs, src/bunit/JSInterop/JSRuntimeInvocationNotSetException.cs, tests/bunit.tests/JSInterop/BunitJSInteropTest.cs
This PR fixes #1746 reported by @RiRiSharp 
Everytime the user forgets to call the setup for the JSRuntime we throw a meaningful exception that something has to be setup.
=> feat: Error when no setup is made for JS

.github/workflows/ci.yml, .github/workflows/docs-deploy.yml, .github/workflows/release.yml, CHANGELOG.md, Directory.Packages.props, bunit.sln, tests/bunit.generators.tests/bunit.generators.tests.csproj, version.json
This PR is created automatically by the bUnit bot.
When completing this PR, it's important to use **Rebase and merge** to keep the commit history clean.
=> Rebase v2 on main

Directory.Packages.props, tests/Directory.Build.props, tests/bunit.generators.tests/Web.AngleSharp/WrapperElementsGeneratorTest.cs, tests/bunit.generators.tests/bunit.generators.tests.csproj, tests/bunit.testassets/DumpCapture.cs, tests/bunit.testassets/Serilog.Sinks.XUnit/TestOutputSink.cs, tests/bunit.testassets/Serilog.Sinks.XUnit/XUnitLoggerConfigurationExtensions.cs, tests/bunit.testassets/ServiceCollectionLoggingExtensions.cs, tests/bunit.testassets/XunitExtensions/RepeatAttribute.cs, tests/bunit.testassets/XunitExtensions/UseCultureAttribute.cs, tests/bunit.testassets/bunit.testassets.csproj, tests/bunit.tests/Rendering/BunitHtmlParserTest.cs
Move our whole test suite from `xunit` to `xunit.v3` (incl. all its dependencies)
=> refactor: use xunit.v3 for test suite
