bUnit-dev/bUnit

- sample/tests/RazorTestComponents/Pages/FetchDataTest.razor
- sample/tests/Tests/Pages/FetchDataTest.cs
- sample/tests/Tests/Pages/TodosTest.cs
- sample/tests/_Imports.razor
- src/Mocking/MockHttpExtensions.cs
- src/Mocking/MockJsRuntimeExtensions.cs
- src/TestContext.cs
- src/TestServiceProvider.cs
- template/template/_Imports.razor
- tests/Components/TestComponentBaseTest/CorrectImplicitRazorTestContextAvailable.razor
- tests/RenderedFragmentTest.cs
- tests/TestServiceProviderTest.cs
- tests/_Imports.razor
> TestServiceProvider now explictly implements IServiceCOlelction

- docs/docs/mocking-jsruntime.md
> Update link in mocking-jsruntime.md

- .github/workflows/deploy-docs.yml
- .github/workflows/main.yml
- docs/samples/components/bunit.docs.samples.csproj
- docs/samples/tests/Directory.Build.props
- src/Directory.Build.props
- src/bunit.core/Extensions/EnumerableExtensions.cs
- src/bunit.web/Extensions/RenderedFragmentExtensions.cs
- src/bunit.web/TestDoubles/JSInterop/JSRuntimeInvocation.cs
- src/bunit.web/TestDoubles/JSInterop/JSRuntimePlannedInvocation.cs
- src/bunit.web/TestDoubles/JSInterop/JSRuntimePlannedInvocationBase.cs
- src/bunit.web/TestDoubles/JSInterop/MissingMockJSRuntimeException.cs
- src/bunit.web/TestDoubles/JSInterop/MockJSRuntimeInvokeHandler.cs
- src/bunit.web/TestDoubles/JSInterop/PlaceholderJSRuntime.cs
- src/bunit.web/TestDoubles/JSInterop/UnplannedJSInvocationException.cs
- src/bunit.xunit/bunit.xunit.csproj
- src/bunit/bunit.csproj
- tests/Directory.Build.props
- tests/bunit.core.tests/Rendering/TestRendererTest.cs
- tests/bunit.testassets/SampleComponents/AsyncRenderOfSubComponentDuringInit.razor
- tests/bunit.testassets/bunit.testassets.csproj
- tests/bunit.xunit.tests/RazorTesting/Mocks.cs
> Net5 rc1 compat

- docs/site/docs/providing-input/inject-services-into-components.md
- docs/site/docs/providing-input/passing-parameters-to-components.md
- docs/site/docs/test-doubles/emulating-ijsruntime.md
- docs/site/docs/test-doubles/mocking-httpclient.md
Small spelling changes on a few of the docs.
> Documentation Spellcheck

- docs/site/docs/test-doubles/emulating-ijsruntime.md
Quick docs change to update from old `SetCompleted` to new `SetVoidResult`
> Update IJSRuntime docs

- CHANGELOG.md
- src/bunit.web/JSInterop/BunitJSInterop.cs
- src/bunit.web/JSInterop/BunitJSInteropSetupExtensions.cs
- src/bunit.web/JSInterop/BunitJSInteropSetupExtensions.net5.cs
- src/bunit.web/JSInterop/InvocationHandlers/Implementation/FocusAsyncInvocationHandler.cs
- src/bunit.web/JSInterop/InvocationHandlers/Implementation/JSObjectReferenceInvocationHandler.cs
- src/bunit.web/JSInterop/InvocationHandlers/Implementation/LooseModeJSObjectReferenceInvocationHandler.cs
- src/bunit.web/JSInterop/InvocationHandlers/Implementation/VirtualizeJSRuntimeInvocationHandler.cs
- src/bunit.web/JSInterop/InvocationHandlers/JSRuntimeInvocationHandler.cs
- src/bunit.web/JSInterop/InvocationHandlers/JSRuntimeInvocationHandlerBase{TResult}.cs
- src/bunit.web/JSInterop/InvocationHandlers/JSRuntimeInvocationHandler{TResult}.cs
- tests/bunit.web.tests/JSInterop/BunitJSInteropTest.cs
- tests/bunit.web.tests/JSInterop/BunitJSObjectReferenceTest.cs
Make it easier to get complete control over invocation matching.
or targeted at `main` branch for documentation that is live on bunit.egilhansen.com.
> Better JSInterop setup

- src/bunit.web/Rendering/RenderedComponent.cs
Small change in RenderedComponent to increase readability. 
*And save some awesome 1 byte*
> Small Boy Scout rule 

- docs/site/docs/verification/semantic-html-comparison.md
Hi @egil
This PR was created because the [docs-deploy](https://github.com/bUnit-dev/bUnit/actions/runs/1755306793) failed to automatically merge stable into main.
> Update main with documentation in stable

- tests/bunit.core.tests/ShouldlyExtensions.cs
I like your project and I want to improve it a bit, good luck in developing your project :)
> refactor: rename generic types in ShouldlyExtensions

- CHANGELOG.md
- Directory.Build.props
- src/bunit.core/Rendering/TestRenderer.cs
- src/bunit.web/EventDispatchExtensions/TriggerEventDispatchExtensions.cs
- src/bunit.web/bunit.web.csproj
- tests/Directory.Build.props
- tests/bunit.web.tests/BlazorE2E/ComponentRenderingTest.cs
- tests/bunit.web.tests/EventDispatchExtensions/GeneralEventDispatchExtensionsTest.cs
- version.json
This PR was created in response to a manual trigger of the [prepare-release workflow](https://github.com/bUnit-dev/bUnit/actions/runs/1882490122).
> Release of new minor version v1.6

- CHANGELOG.md
- docs/README.md
Fixed the step by step guide to include how to setup up DocFx to run and view the documentation locally.
> fix: Change step by step guide to include setup of DocFx

- docs/site/docs/misc-test-tips.md
The updated link is specifically for Visual Studio 2022, but the page also has a link to the older, Visual Studio 2019 version.
> docs: Updated link to SmartPaster in misc-test-tips.md

- .github/workflows/docs-deploy.yml
- .github/workflows/release-preview.yml
- .github/workflows/verification-dotnet-nightly.yml
- .github/workflows/verification.yml
Adding colors as described in #691
Sample output can be seen [here](https://github.com/linkdotnet/bUnit/runs/6205632557?check_suite_focus=true#step:8:74) or [here](https://github.com/bUnit-dev/bUnit/pull/693/checks#step:11:59).
> feat: added color output on .net related actions

- src/bunit.web/Rendering/Internal/Htmlizer.cs
Small PR which uses `ReadOnlySpan` instead of `ArraySegment` in `Htmlizer`.
I do feel it is more readable / less error prone now because we get rid of `ref var frame = ref ...` because we are working directly with the contiguous slice of memory.  There are neglectable small improvements of performance as well but this was not my main motivation.
> refactor: use ReadOnlySpan instead of ArraySegment

- CHANGELOG.md
- src/bunit.core/Extensions/WaitForHelpers/RenderedFragmentWaitForHelperExtensions.cs
- src/bunit.core/Extensions/WaitForHelpers/WaitForHelper.cs
- src/bunit.core/Rendering/TestRenderer.cs
- src/bunit.core/Rendering/UnknownEventHandlerIdException.cs
- src/bunit.web/EventDispatchExtensions/TriggerEventDispatchExtensions.cs
- tests/.editorconfig
- tests/bunit.core.tests/Rendering/TestRendererTest.cs
- tests/bunit.testassets/SampleComponents/CounterComponentDynamic.razor
- tests/bunit.web.tests/EventDispatchExtensions/GeneralEventDispatchExtensionsTest.cs
- tests/run-tests.ps1
> Trigger event race condition with DOM update

- CHANGELOG.md
Correct url in changelog, no real code changes.
> Correct url in changelog

- .github/workflows/release-preview.yml
- .github/workflows/verification-dotnet-nightly.yml
- .github/workflows/verification.yml
- CHANGELOG.md
- Directory.Build.props
- src/AngleSharpWrappers/AngleSharpWrappers.csproj
- src/Directory.Build.props
- src/bunit.core/Extensions/WaitForHelpers/RenderedFragmentWaitForHelperExtensions.cs
- src/bunit.core/Extensions/WaitForHelpers/WaitForHelper.cs
- src/bunit.core/Extensions/WaitForHelpers/WaitForHelperLoggerExtensions.cs
- src/bunit.core/Rendering/TestRenderer.cs
- src/bunit.core/Rendering/UnknownEventHandlerIdException.cs
- src/bunit.web/EventDispatchExtensions/TriggerEventDispatchExtensions.cs
- src/bunit.web/bunit.web.csproj
- tests/.editorconfig
- tests/bunit.core.tests/Extensions/WaitForHelpers/RenderedFragmentWaitForHelperExtensionsTest.cs
- tests/bunit.core.tests/Rendering/TestRendererTest.cs
- tests/bunit.core.tests/TestContextBaseTest.net5.cs
- tests/bunit.testassets/AssertExtensions/TaskAssertionExtensions.cs
- tests/bunit.testassets/SampleComponents/CounterComponentDynamic.razor
- tests/bunit.web.tests/BlazorE2E/ComponentRenderingTest.cs
- tests/bunit.web.tests/EventDispatchExtensions/GeneralEventDispatchExtensionsTest.cs
- tests/bunit.web.tests/Extensions/WaitForHelpers/RenderedFragmentWaitForElementsHelperExtensionsTest.cs
- tests/run-tests.ps1
- version.json
This PR was created in response to a manual trigger of the [prepare-release workflow](https://github.com/bUnit-dev/bUnit/actions/runs/2454017114).
> Release of new minor version v1.9

- .github/workflows/verification-dotnet-nightly.yml
- .github/workflows/verification.yml
There were some projects not tested on CI/CD runs.
We should merge this after #754 to test if that works :D
> fix: Added missing test projects in CI/CD

- .github/workflows/verification-dotnet-nightly.yml
Whitespace issue in yml file for nightly job
> fix: whitespace issue in nightly job

- .gitignore
Ignore that weird `.DS_Store` file which is created on MacOS
> add: Ignore MacOS files

- docs/samples/tests/razor/bunit.docs.razor.samples.csproj
- docs/samples/tests/xunit/bunit.docs.xunit.samples.csproj
- docs/site/docs/getting-started/create-test-project.md
- src/bunit.template/template/Company.BlazorTests1.csproj
- src/bunit.web.testcomponents/bunit.web.testcomponents.csproj
- tests/Directory.Build.props
- tests/bunit.testassets/bunit.testassets.csproj
- tests/bunit.web.testcomponents.tests/bunit.web.testcomponents.tests.csproj
Updated all xUnit versions in a central PR as dependabot seems to have trouble on this one.
Also aligned the versions in the documentation and template-projects.
> refactor: Updated and aligned xunit versions

- tests/bunit.web.tests/JSInterop/BunitJSInteropTest.net5.cs
On my last PR, regarding suppression, one file slipped through. My local machine didn't show any warning/errors in release in this file. Anyway here we go ;)
Fixes #823
> fix: Add suppression to net5 file

- CHANGELOG.md
- docs/site/docs/test-doubles/fake-webassemblyhostenvironment.md
- docs/site/docs/test-doubles/index.md
- docs/site/docs/toc.md
- src/bunit.web/Extensions/TestServiceProviderExtensions.cs
- src/bunit.web/TestDoubles/WebAssemblyHostEnvironment/FakeWebAssemblyHostEnvironment.cs
- src/bunit.web/bunit.web.csproj
- tests/bunit.testassets/SampleComponents/SimpleUsingWebAssemblyHostEnvironment.razor
- tests/bunit.testassets/_Imports.razor
- tests/bunit.testassets/bunit.testassets.csproj
- tests/bunit.web.tests/TestDoubles/FakeWebAssemblyHostEnvironmentTest.cs
> Added FakeWebAssembleHostEnvironment, tests, and docs.

- src/bunit.core/Extensions/WaitForHelpers/WaitForHelper.cs
After reading this thread (https://twitter.com/davidfowl/status/1572800836052586496) on Twitter, I realized that the WaitForHelper was not cancelling the Task.Delay timer (https://twitter.com/davidfowl/status/1572817384624488449).
Switching over to a Timer class instead should solve the problem, but we need to run some stress tests against this change.
> fix: ensure timeout timer is disposed in WaitForHelper

- docs/site/docs/getting-started/create-test-project.md
Resolve #869
Changed the source branche according to #875 and fix the documentation as suggested in #869
> Rework the documentation page

- src/bunit.core/ComponentParameterCollectionBuilder.cs
- src/bunit.core/ComponentParameterFactory.cs
- src/bunit.core/Extensions/BlazorExtensions.cs
- src/bunit.core/StringSyntaxAttribute.cs
- src/bunit.web/Asserting/MarkupMatchesAssertExtensions.cs
- src/bunit.web/Extensions/StubComponentFactoryCollectionExtensions.cs
- src/bunit.web/Rendering/BunitHtmlParser.cs
- src/bunit.web/TestDoubles/NavigationManager/NavigationHistory.cs
> feat: Added StringSyntax support so that IDE's help out the user

- CHANGELOG.md
- src/bunit.web/Rendering/Internal/Htmlizer.cs
- tests/bunit.testassets/BlazorE2E/ComponentWithEscapableCharacters.razor
- tests/bunit.web.tests/BlazorE2E/ComponentRenderingTest.cs
> fix: Don't encode characters. (Fixes #898)

- Directory.Build.props
- tests/Directory.Build.props
- tests/bunit.testassets/bunit.testassets.csproj
This PR updates to the .net7 GA release.
> chore: Update to net7 GA

- .github/dependabot.yml
This PR will use dependabot to update our actions! Simpler than the approach before and more maintainable.
> feat: Dependabot check for actions

- CHANGELOG.md
- Directory.Build.props
- README.md
- benchmark/bunit.benchmarks/bunit.benchmarks.csproj
- src/bunit.web/Extensions/TestServiceProviderExtensions.cs
- src/bunit.web/Rendering/Internal/Htmlizer.cs
- src/bunit.web/TestDoubles/NavigationManager/FakeNavigationManager.cs
- src/bunit.web/bunit.web.csproj
- tests/Directory.Build.props
- tests/bunit.testassets/BlazorE2E/ComponentWithEscapableCharacters.razor
- tests/bunit.web.tests/BlazorE2E/ComponentRenderingTest.cs
- tests/bunit.web.tests/TestDoubles/NavigationManager/FakeNavigationManagerTest.cs
- version.json
This PR was created in response to a manual trigger of the [prepare-release workflow](https://github.com/bUnit-dev/bUnit/actions/runs/3895960078).
> Release of new minor version v1.14

- CHANGELOG.md
- src/bunit.web/Diffing/BlazorDiffingHelpers.cs
- src/bunit.web/Diffing/HtmlComparer.cs
- tests/bunit.testassets/SampleComponents/SimpleSvg.razor
- tests/bunit.testassets/XunitExtensions/TheoryDataExtensions.cs
- tests/bunit.web.tests/Asserting/MarkupMatchesAssertExtensionsTest.cs
- tests/bunit.web.tests/Rendering/BunitHtmlParserTest.cs
- version.json
This PR was created in response to a manual trigger of the [prepare-release workflow](https://github.com/bUnit-dev/bUnit/actions/runs/4118466330).
> Release of new minor version v1.16

- docs/site/docs/test-doubles/input-file.md
This PR fixes a small bug in the docs.
> fix: wrong type assignment in doc

- .github/workflows/release-preview.yml
- .github/workflows/release.yml
- .github/workflows/verification.yml
Let's trigger the build-pipeline once more
> refactor: Use PackageOutputPath instead of -o

- .github/workflows/release-preview.yml
- .github/workflows/release.yml
- .github/workflows/verification.yml
- CHANGELOG.md
- benchmark/bunit.benchmarks/bunit.benchmarks.csproj
- src/bunit.web/EventDispatchExtensions/TriggerEventDispatchExtensions.cs
- tests/bunit.testassets/SampleComponents/SubmitFormOnClick.razor
- tests/bunit.testassets/bunit.testassets.csproj
- tests/bunit.web.tests/EventDispatchExtensions/GeneralEventDispatchExtensionsTest.cs
- version.json
This PR was created in response to a manual trigger of the [prepare-release workflow](https://github.com/bUnit-dev/bUnit/actions/runs/4240315709).
> Release of new minor version v1.17

- CHANGELOG.md
- src/bunit.web/Rendering/Internal/Htmlizer.cs
- tests/bunit.testassets/BlazorE2E/ComponentWithEscapableCharacters.razor
- tests/bunit.web.tests/BlazorE2E/ComponentRenderingTest.cs
> Escape char bug

- .editorconfig
- CHANGELOG.md
- Directory.Build.props
- src/.editorconfig
- src/bunit.web/ComponentFactories/StubComponentFactory.cs
- src/bunit.web/EventDispatchExtensions/TriggerEventDispatchExtensions.cs
- src/bunit.web/Rendering/Internal/Htmlizer.cs
- tests/.editorconfig
- tests/Directory.Build.props
- tests/bunit.core.tests/ComponentParameterCollectionBuilderTests.cs
- tests/bunit.testassets/BlazorE2E/ComponentWithEscapableCharacters.razor
- tests/bunit.testassets/SampleComponents/ButtonsInsideForm.razor
- tests/bunit.testassets/SampleComponents/SubmitFormOnClick.razor
- tests/bunit.web.tests/BlazorE2E/ComponentRenderingTest.cs
- tests/bunit.web.tests/EventDispatchExtensions/GeneralEventDispatchExtensionsTest.cs
- tests/bunit.web.tests/EventDispatchExtensions/InputEventDispatchExtensionsTest.cs
- version.json
This PR was created in response to a manual trigger of the [prepare-release workflow](https://github.com/bUnit-dev/bUnit/actions/runs/4274058997).
> Release of new minor version v1.18

- CHANGELOG.md
- src/bunit.web/Diffing/BlazorDiffingHelpers.cs
- tests/bunit.testassets/SampleComponents/CustomElementWithAttribute.razor
- tests/bunit.web.tests/Asserting/MarkupMatchesAssertExtensionsTest.cs
> fix: Custom elements with attributes throw exception

- src/bunit.web/Diffing/HtmlComparer.cs
- tests/bunit.testassets/SampleComponents/CustomElement.razor
- tests/bunit.testassets/SampleComponents/CustomElementWithAttribute.razor
- tests/bunit.web.tests/Asserting/MarkupMatchesAssertExtensionsTest.cs
Naming things is hard - my apologies
> fix: Better naming for test method

- docs/site/index.md
> Merge stable into main

- src/bunit/Rendering/RootComponent.cs
- src/bunit/Rendering/TestRenderer.cs
Only partially related to #1068: A small simplification of how we dispose components.
> refactor: simplify disposecomponents

- src/bunit/Rendering/TestRenderer.cs
Small refactoring for `FindComponents` to use a generator function to make the code easier.
> Simplify find component

- src/bunit/Extensions/TestRendererExtensions.cs
- src/bunit/Rendering/BunitRenderer.cs
I did not migrate XML-doc's when I removed the `ITestRenderer` interface - therefore, let's add them again.
> Fix xml doc

- src/bunit/ComponentParameterCollection.cs
A small refactoring I came across that only needed one pass-through to get duplicates. Plus points for hopefully better readability of the code itself.
EDIT: Continued a bit
> refactor: Check for duplicates in one pass-through

- docs/site/docs/providing-input/substituting-components.md
Closes #1123 
Fix small code issue in docs.
> fix: Wrong code in documentation

- docs/samples/tests/nunit/HelloWorldInstancePerTestCase.cs
- docs/samples/tests/nunit/HelloWorldRazorInstancePerTestCase.razor
- docs/samples/tests/nunit/bunit.docs.nunit.samples.csproj
- docs/site/docs/getting-started/writing-tests.md
> docs: Show new LifeCycle attribute

- docs/site/index.md
Updated outdated description of bunit.template on index.html of [bunit.](https://bunit.dev/)
Is available for NUnit and MSTest too ;-)
> Updated outdated description of bunit.template

- src/bunit/IRenderedFragment.cs
- src/bunit/Rendering/RenderedComponent.cs
- src/bunit/Rendering/RenderedFragment.cs
- src/bunit/bunit.csproj
Small cleanup (also stuff we saw yesterday).
> refactor: Smaller cleanups

- Directory.Build.props
- src/bunit.template/template/Company.BlazorTests1.csproj
- tests/Directory.Build.props
- tests/bunit.testassets/bunit.testassets.csproj
- tests/bunit.tests/Rendering/BunitRendererTest.cs
- tests/bunit.tests/TestDoubles/BunitSignOutSessionStateManagerTest.cs
Bump packages and fixes new xUnit analyzers.
> chore: Bump packages and fix analyzers

- CHANGELOG.md
- src/bunit.core/TestContextBase.cs
> fix: ensure renderer is disposed as the before any other services or the service provider

- CHANGELOG.md
- src/bunit.web/EventDispatchExtensions/DialogEventDispatchExtensions.cs
> feat: Trigger OnCancel and OnClose event on dialog

- .github/workflows/verification.yml
- bunit.sln
- src/bunit.web.query/bunit.web.query.csproj
- tests/Directory.Build.props
- tests/bunit.web.query.tests/bunit.web.query.tests.csproj
Hey @linkdotnet, @scottsauber, here is a PR adding the bunit.web.query package. That should give you a good starting point to add testing libs APIs.
> add bunit.web.query

- CHANGELOG.md
Better changelog for the last commit
> fix: Better changelog entry

- CHANGELOG.md
- src/bunit.web/TestDoubles/NavigationManager/FakeNavigationManager.cs
- tests/bunit.web.tests/TestDoubles/NavigationManager/FakeNavigationManagerTest.cs
> feat: Set HistoryEntryState in NavigationManager

- .github/workflows/ci.yml
> ci: only release preview on manual dispatch from main or v2

- docs/site/docs/extensions/bunit-generators.md
- src/bunit.generators/Web.Stubs/AttributeStubGenerator/ComponentStubAttributeGenerator.cs
- tests/bunit.generators.tests/Web.Stub/AddStubGeneratorTests.cs
We would help out users, if we report some diagnostics for our generators.
> feat: Add diagnostics for source generators

- docs/site/docs/providing-input/passing-parameters-to-components.md
> docs: Added examples for query strings in net8

- .github/workflows/ci.yml
- .github/workflows/docs-deploy.yml
- .github/workflows/release.yml
- CHANGELOG.md
- Directory.Build.props
- bunit.sln
- global.json
- src/bunit.core/bunit.core.csproj
- src/bunit.web.query/bunit.web.query.csproj
- src/bunit.web/JSInterop/Implementation/BunitJSObjectReference.cs
- src/bunit.web/JSInterop/Implementation/BunitJSRuntime.net5.cs
- src/bunit.web/JSInterop/JSRuntimeInvocation.cs
- src/bunit.web/bunit.web.csproj
- src/bunit/bunit.csproj
- tests/bunit.core.tests/bunit.core.tests.csproj
- tests/bunit.testassets/bunit.testassets.csproj
- tests/bunit.web.query.tests/bunit.web.query.tests.csproj
- tests/bunit.web.tests/JSInterop/BunitJSInteropTest.net5.cs
- tests/bunit.web.tests/JSInterop/BunitJSObjectReferenceTest.cs
- tests/bunit.web.tests/bunit.web.tests.csproj
> feat: Added support for net9.0

- MIGRATION.md
- docs/samples/tests/xunit/MockHttpClientBunitHelpers.cs
- docs/site/docs/providing-input/inject-services-into-components.md
- src/bunit/Asserting/MarkupMatchesAssertExtensions.cs
- src/bunit/BunitContext.cs
- src/bunit/BunitServiceProvider.cs
- src/bunit/Extensions/BunitServiceProviderExtensions.cs
- src/bunit/Rendering/BunitRenderer.cs
- src/bunit/Rendering/RenderedFragment.cs
- src/bunit/TestDoubles/Authorization/BunitAuthorizationContext.cs
- src/bunit/TestDoubles/Authorization/BunitAuthorizationExtensions.cs
- src/bunit/TestDoubles/PersistentComponentState/BunitPersistentComponentState.cs
- tests/bunit.tests/BunitServiceProviderTests.cs
> refactor: Rename TestServiceProvider to BunitServiceProvider

- CHANGELOG.md
- src/bunit.web/Rendering/BunitHtmlParser.cs
- tests/bunit.web.tests/Rendering/BunitHtmlParserTest.cs
> fix: correctly parse html that starts with a <!DOCTYPE html> element

- src/bunit/Rendering/BunitRenderer.cs
- src/bunit/Rendering/IRenderedComponent.cs
- src/bunit/Rendering/Internal/Htmlizer.cs
- src/bunit/Rendering/RenderedComponent.cs
> Feature component state

- src/bunit/Rendering/BunitRenderer.cs
Small perf improvement - caching the ConstructorInfo.
we could go even further and have an immutable copy of the initial RenderedConponent<TComponent> and clone it every time.
> Cache ctor info

- .github/workflows/ci.yml
- .github/workflows/docs-deploy.yml
- .github/workflows/prepare-release.yml
- .github/workflows/release.yml
- Directory.Build.props
- src/Directory.Build.props
- src/bunit.core/TestContextBase.cs
- src/bunit.generators.internal/bunit.generators.internal.csproj
- src/bunit.generators/bunit.generators.csproj
- src/bunit.template/template/Company.BlazorTests1.csproj
- src/bunit.web.query/bunit.web.query.csproj
- src/bunit.web/bunit.web.csproj
- tests/.editorconfig
- tests/Directory.Build.props
- tests/bunit.core.tests/bunit.core.tests.csproj
- tests/bunit.generators.tests/bunit.generators.tests.csproj
- tests/bunit.testassets/bunit.testassets.csproj
- tests/bunit.web.query.tests/bunit.web.query.tests.csproj
- tests/bunit.web.tests/bunit.web.tests.csproj
> chore: Update deps

- docs/site/docs/providing-input/inject-services-into-components.md
> docs: Add Loose Automocker description

- .github/workflows/ci.yml
> fix: Replace Tokens in docfx.json for release information

- .devcontainer/devcontainer.json
- .github/workflows/ci.yml
- CHANGELOG.md
- Directory.Build.props
- benchmark/bunit.benchmarks.assets/bunit.benchmarks.assets.csproj
- docs/samples/tests/Directory.Build.props
- docs/samples/tests/razor/bunit.docs.razor.samples.csproj
- docs/samples/tests/xunit/bunit.docs.xunit.samples.csproj
- src/bunit.template/template/Company.BlazorTests1.csproj
- src/bunit.web/Extensions/InputFile/BUnitBrowserFile.cs
- src/bunit.web/Extensions/InputFile/InputFileExtensions.cs
- src/bunit.web/bunit.web.csproj
- tests/Directory.Build.props
- tests/bunit.core.tests/bunit.core.tests.csproj
- tests/bunit.generators.tests/bunit.generators.tests.csproj
- tests/bunit.testassets/SampleComponents/PersistentComponentStateSample.razor.cs
- tests/bunit.testassets/_Imports.razor
- tests/bunit.testassets/bunit.testassets.csproj
- tests/bunit.web.query.tests/bunit.web.query.tests.csproj
- tests/bunit.web.tests/Extensions/InputFile/InputFileTests.cs
- tests/bunit.web.tests/bunit.web.tests.csproj
- version.json
This PR was created in response to a manual trigger of the [prepare-release workflow](https://github.com/bUnit-dev/bUnit/actions/runs/10014231507).
> Release of new minor version v1.30

- .github/workflows/release.yml
- src/Directory.Build.props
- src/bunit.generators.internal/bunit.generators.internal.csproj
- src/bunit.generators/bunit.generators.csproj
- src/bunit.template/template/Company.BlazorTests1.csproj
- tests/Directory.Build.props
- tests/bunit.generators.tests/bunit.generators.tests.csproj
Upgrade to latest and greatest to bundle all the dependabot PR's
> chore: Bump packages

- .config/dotnet-tools.json
- CHANGELOG.md
- Directory.Packages.props
- src/bunit.core/Rendering/BunitComponentActivator.cs
- src/bunit.core/Rendering/TestRenderer.cs
- src/bunit.generators/Web.Stubs/AddStubMethodStubGenerator/AddStubGenerator.cs
- src/bunit.generators/Web.Stubs/AttributeStubGenerator/ComponentStubAttributeGenerator.cs
- src/bunit.generators/Web.Stubs/MemberRetriever.cs
- tests/bunit.generators.tests/Web.Stub/AddStubGeneratorTests.cs
- tests/bunit.generators.tests/Web.Stub/Components/ContainerComponent.cs
- tests/bunit.testassets/SampleComponents/ConstructorInjectionComponent.cs
- tests/bunit.web.tests/Rendering/RenderedComponentTest.cs
- version.json
This PR was created in response to a manual trigger of the [prepare-release workflow](https://github.com/bUnit-dev/bUnit/actions/runs/11293811230).
> Release of new minor version v1.33

- .github/workflows/release.yml
- CHANGELOG.md
Our extensions are almost 1 year old - time to release them to the public!
> feat: Flag extensions as stable

- .config/dotnet-tools.json
- .github/workflows/ci.yml
- .github/workflows/release.yml
- CHANGELOG.md
- Directory.Packages.props
- src/Directory.Build.props
- src/bunit.template/template/.template.config/template.json
- src/bunit.template/template/Company.BlazorTests1.csproj
- version.json
This PR was created in response to a manual trigger of the [prepare-release workflow](https://github.com/bUnit-dev/bUnit/actions/runs/11804902850).
> Release of new minor version v1.35

- .devcontainer/devcontainer.json
- .devcontainer/post-install.sh
- CHANGELOG.md
- Directory.Packages.props
- global.json
- version.json
This PR was created in response to a manual trigger of the [prepare-release workflow](https://github.com/bUnit-dev/bUnit/actions/runs/11805252930).
> Release of new minor version v1.36

- .config/dotnet-tools.json
- Directory.Packages.props
> chore: Update packages

- src/bunit/Diffing/DiffMarkupFormatter.cs
> chore: Remove obsolete property

- CHANGELOG.md
- src/bunit.core/Rendering/TestRenderer.cs
- tests/bunit.web.tests/Rendering/RenderedComponentTest.cs
Fixes #1691 
Has to be merged to `v2`
> fix: Add test for FindComponents with base and derived components

- .github/workflows/ci.yml
- .github/workflows/docs-deploy.yml
- .github/workflows/release.yml
- CHANGELOG.md
- Directory.Packages.props
- bunit.sln
- tests/bunit.generators.tests/bunit.generators.tests.csproj
- version.json
This PR was created in response to a manual trigger of the [prepare-release workflow](https://github.com/bUnit-dev/bUnit/actions/runs/15653081570).
> Release of new minor version v1.40

- docs/site/docs/providing-input/inject-services-into-components.md
Fix line number in example for injecting services. Now from and to the correct branch
> Fix line number in example for injecting services
